name: Package the commits on the development branches

on:
  push:
    branches:
      - dev
      - alpha/*
      - beta/*
      - release/*
      - hotfix/*
      - feature/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the addon
        uses: actions/checkout@v4

      - name: Create the package
        uses: BigWigsMods/packager@master
        with:
          args: -d -z

      - name: Upload the package as artifact
        uses: actions/upload-artifact@v4
        with:
          name: TrilliaxScrubber-${{ github.sha }}
          include-hidden-files: true
          path: .release/
