name: Package the pull requests

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the addon
        uses: actions/checkout@v4

      - name: Create the package
        uses: BigWigsMods/packager@master
        with:
          args: -d -z

      - name: Upload the package as artifact
        uses: actions/upload-artifact@v4
        with:
          name: TrilliaxScrubber-pr${{ github.event.number }}
          include-hidden-files: true
          path: .release/
